### ISSUE TITLE
Timer coundown

### ISSUE THREAD

**Issue by irfanzidny** [slametbsan/kelulusan#2]
Pak, timer countdown hanya berfungsi untuk 24 jam ya? Saya coba set konfigurasi pengumuman untuk 5 Juni 2020, tetapi di halaman utama yang muncul tetap hitungan dalam satu hari. Sehingga esok harinya sudah terbuka lagi..

**Comment by slametbsan** [comment]
ya, pengumuman biasanya dipersiapkan 24 jam sebelum rapat pleno. bisa anda edit sendiri file index.php dan edit baris ke-137 seperti berikut:
`<span>%D Hari %H Jam %M Menit %S Detik</span>`

intinya tambahkan tampilan `%D Hari` cuman efeknya jika timer sudah kurang dari 24 jam, akan tampil kurang lebih seperti ini **0 Hari 23 Jam 23 Menit 23 Detik**.

Demo-nya seperti ini: [slametbsan.my.id/demo/kelulusan/](http://slametbsan.my.id/demo/kelulusan/)
